/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as ModeloRouteImport } from './routes/modelo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditarTokenRouteImport } from './routes/editar.$token'

const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeloRoute = ModeloRouteImport.update({
  id: '/modelo',
  path: '/modelo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarTokenRoute = EditarTokenRouteImport.update({
  id: '/editar/$token',
  path: '/editar/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/modelo': typeof ModeloRoute
  '/modelos': typeof ModelosRoute
  '/editar/$token': typeof EditarTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/modelo': typeof ModeloRoute
  '/modelos': typeof ModelosRoute
  '/editar/$token': typeof EditarTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/modelo': typeof ModeloRoute
  '/modelos': typeof ModelosRoute
  '/editar/$token': typeof EditarTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/modelo'
    | '/modelos'
    | '/editar/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$slug' | '/admin' | '/modelo' | '/modelos' | '/editar/$token'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/modelo'
    | '/modelos'
    | '/editar/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRoute
  ModeloRoute: typeof ModeloRoute
  ModelosRoute: typeof ModelosRoute
  EditarTokenRoute: typeof EditarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelo': {
      id: '/modelo'
      path: '/modelo'
      fullPath: '/modelo'
      preLoaderRoute: typeof ModeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar/$token': {
      id: '/editar/$token'
      path: '/editar/$token'
      fullPath: '/editar/$token'
      preLoaderRoute: typeof EditarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRoute,
  ModeloRoute: ModeloRoute,
  ModelosRoute: ModelosRoute,
  EditarTokenRoute: EditarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
