/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as ModeloRouteImport } from './routes/modelo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelosIndexRouteImport } from './routes/modelos.index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as ModelosSlugRouteImport } from './routes/modelos.$slug'
import { Route as EditarTokenRouteImport } from './routes/editar.$token'
import { Route as SlugAdminRouteImport } from './routes/$slug.admin'

const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeloRoute = ModeloRouteImport.update({
  id: '/modelo',
  path: '/modelo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosIndexRoute = ModelosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelosRoute,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const ModelosSlugRoute = ModelosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ModelosRoute,
} as any)
const EditarTokenRoute = EditarTokenRouteImport.update({
  id: '/editar/$token',
  path: '/editar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugAdminRoute = SlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/modelo': typeof ModeloRoute
  '/modelos': typeof ModelosRouteWithChildren
  '/$slug/admin': typeof SlugAdminRoute
  '/editar/$token': typeof EditarTokenRoute
  '/modelos/$slug': typeof ModelosSlugRoute
  '/$slug/': typeof SlugIndexRoute
  '/modelos/': typeof ModelosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/modelo': typeof ModeloRoute
  '/$slug/admin': typeof SlugAdminRoute
  '/editar/$token': typeof EditarTokenRoute
  '/modelos/$slug': typeof ModelosSlugRoute
  '/$slug': typeof SlugIndexRoute
  '/modelos': typeof ModelosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/modelo': typeof ModeloRoute
  '/modelos': typeof ModelosRouteWithChildren
  '/$slug/admin': typeof SlugAdminRoute
  '/editar/$token': typeof EditarTokenRoute
  '/modelos/$slug': typeof ModelosSlugRoute
  '/$slug/': typeof SlugIndexRoute
  '/modelos/': typeof ModelosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/modelo'
    | '/modelos'
    | '/$slug/admin'
    | '/editar/$token'
    | '/modelos/$slug'
    | '/$slug/'
    | '/modelos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/modelo'
    | '/$slug/admin'
    | '/editar/$token'
    | '/modelos/$slug'
    | '/$slug'
    | '/modelos'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/modelo'
    | '/modelos'
    | '/$slug/admin'
    | '/editar/$token'
    | '/modelos/$slug'
    | '/$slug/'
    | '/modelos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AdminRoute: typeof AdminRoute
  ModeloRoute: typeof ModeloRoute
  ModelosRoute: typeof ModelosRouteWithChildren
  EditarTokenRoute: typeof EditarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelo': {
      id: '/modelo'
      path: '/modelo'
      fullPath: '/modelo'
      preLoaderRoute: typeof ModeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos/': {
      id: '/modelos/'
      path: '/'
      fullPath: '/modelos/'
      preLoaderRoute: typeof ModelosIndexRouteImport
      parentRoute: typeof ModelosRoute
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/modelos/$slug': {
      id: '/modelos/$slug'
      path: '/$slug'
      fullPath: '/modelos/$slug'
      preLoaderRoute: typeof ModelosSlugRouteImport
      parentRoute: typeof ModelosRoute
    }
    '/editar/$token': {
      id: '/editar/$token'
      path: '/editar/$token'
      fullPath: '/editar/$token'
      preLoaderRoute: typeof EditarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/admin': {
      id: '/$slug/admin'
      path: '/admin'
      fullPath: '/$slug/admin'
      preLoaderRoute: typeof SlugAdminRouteImport
      parentRoute: typeof SlugRoute
    }
  }
}

interface SlugRouteChildren {
  SlugAdminRoute: typeof SlugAdminRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugAdminRoute: SlugAdminRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface ModelosRouteChildren {
  ModelosSlugRoute: typeof ModelosSlugRoute
  ModelosIndexRoute: typeof ModelosIndexRoute
}

const ModelosRouteChildren: ModelosRouteChildren = {
  ModelosSlugRoute: ModelosSlugRoute,
  ModelosIndexRoute: ModelosIndexRoute,
}

const ModelosRouteWithChildren =
  ModelosRoute._addFileChildren(ModelosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AdminRoute: AdminRoute,
  ModeloRoute: ModeloRoute,
  ModelosRoute: ModelosRouteWithChildren,
  EditarTokenRoute: EditarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
