ALTER TABLE public.restaurants 
ADD COLUMN IF NOT EXISTS header_style TEXT DEFAULT 'standard',
ADD COLUMN IF NOT EXISTS category_layout TEXT DEFAULT 'pills',
ADD COLUMN IF NOT EXISTS product_card_layout TEXT DEFAULT 'list',
ADD COLUMN IF NOT EXISTS background_color TEXT DEFAULT '#FDF5E6',
ADD COLUMN IF NOT EXISTS text_color TEXT DEFAULT '#3B2C24',
ADD COLUMN IF NOT EXISTS show_search BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS show_categories BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS custom_css TEXT;